package com.piremote.app.data.agent

import java.io.File
import java.io.FileOutputStream
import java.nio.charset.StandardCharsets
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Native Office OpenXML (.docx and .pptx) document generator.
 * Runs purely on JVM without external Python, Node.js, or heavy office binaries.
 */
object OfficeDocumentBuilder {

    data class WordSection(
        val heading: String? = null,
        val level: Int = 1, // 1: H1, 2: H2, 3: H3
        val paragraphs: List<String> = emptyList(),
        val bullets: List<String> = emptyList(),
        val tableHeaders: List<String> = emptyList(),
        val tableRows: List<List<String>> = emptyList(),
    )

    data class PptSlide(
        val title: String,
        val subtitle: String? = null,
        val bullets: List<String> = emptyList(),
        val notes: String? = null,
    )

    /**
     * Generates a fully compliant, styled Word document (.docx).
     */
    fun createDocx(
        outputFile: File,
        title: String,
        subtitle: String? = null,
        author: String? = null,
        sections: List<WordSection>,
    ): Boolean {
        outputFile.parentFile?.mkdirs()
        return try {
            ZipOutputStream(FileOutputStream(outputFile)).use { zip ->
                // 1. [Content_Types].xml
                zipPut(zip, "[Content_Types].xml", buildDocxContentTypes())

                // 2. _rels/.rels
                zipPut(zip, "_rels/.rels", buildDocxRootRels())

                // 3. word/_rels/document.xml.rels
                zipPut(zip, "word/_rels/document.xml.rels", buildDocxDocumentRels())

                // 4. word/styles.xml
                zipPut(zip, "word/styles.xml", buildDocxStyles())

                // 5. word/document.xml
                zipPut(zip, "word/document.xml", buildDocxDocumentXml(title, subtitle, author, sections))
            }
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    /**
     * Generates a fully compliant PowerPoint presentation (.pptx).
     */
    fun createPptx(
        outputFile: File,
        title: String,
        subtitle: String? = null,
        slides: List<PptSlide>,
    ): Boolean {
        outputFile.parentFile?.mkdirs()
        return try {
            val allSlides = mutableListOf<PptSlide>()
            // Cover slide
            allSlides.add(PptSlide(title = title, subtitle = subtitle ?: "Generated by Pi Remote AI Agent"))
            allSlides.addAll(slides)

            ZipOutputStream(FileOutputStream(outputFile)).use { zip ->
                // 1. [Content_Types].xml
                zipPut(zip, "[Content_Types].xml", buildPptxContentTypes(allSlides.size))

                // 2. _rels/.rels
                zipPut(zip, "_rels/.rels", buildPptxRootRels())

                // 3. ppt/_rels/presentation.xml.rels
                zipPut(zip, "ppt/_rels/presentation.xml.rels", buildPptxPresentationRels(allSlides.size))

                // 4. ppt/presentation.xml
                zipPut(zip, "ppt/presentation.xml", buildPptxPresentationXml(allSlides.size))

                // 5. Slides
                for (i in allSlides.indices) {
                    val slideNum = i + 1
                    zipPut(zip, "ppt/slides/_rels/slide$slideNum.xml.rels", buildPptxSlideRels())
                    zipPut(zip, "ppt/slides/slide$slideNum.xml", buildPptxSlideXml(allSlides[i], isCover = i == 0))
                }
            }
            true
        } catch (e: Exception) {
            e.printStackTrace()
            false
        }
    }

    private fun zipPut(zip: ZipOutputStream, entryName: String, content: String) {
        val entry = ZipEntry(entryName)
        zip.putNextEntry(entry)
        zip.write(content.toByteArray(StandardCharsets.UTF_8))
        zip.closeEntry()
    }

    private fun escapeXml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
    }

    // ---------------------------------------------------------------- DOCX XML Generators

    private fun buildDocxContentTypes(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>"""

    private fun buildDocxRootRels(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>"""

    private fun buildDocxDocumentRels(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>"""

    private fun buildDocxStyles(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults>
    <w:rPrDefault>
      <w:rPr>
        <w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:eastAsia="Microsoft YaHei"/>
        <w:sz w:val="22"/>
        <w:color w:val="2B2B2B"/>
      </w:rPr>
    </w:rPrDefault>
  </w:docDefaults>
</w:styles>"""

    private fun buildDocxDocumentXml(
        title: String,
        subtitle: String?,
        author: String?,
        sections: List<WordSection>,
    ): String {
        val sb = StringBuilder()
        sb.append("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
""")

        // Title
        sb.append("""
    <w:p>
      <w:pPr><w:jc w:val="center"/><w:spacing w:before="360" w:after="160"/></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="52"/><w:color w:val="0F172A"/></w:rPr><w:t>${escapeXml(title)}</w:t></w:r>
    </w:p>
""")

        // Subtitle / Author
        if (!subtitle.isNullOrBlank()) {
            sb.append("""
    <w:p>
      <w:pPr><w:jc w:val="center"/><w:spacing w:after="80"/></w:pPr>
      <w:r><w:rPr><w:sz w:val="26"/><w:color w:val="64748B"/></w:rPr><w:t>${escapeXml(subtitle)}</w:t></w:r>
    </w:p>
""")
        }
        if (!author.isNullOrBlank()) {
            sb.append("""
    <w:p>
      <w:pPr><w:jc w:val="center"/><w:spacing w:after="360"/></w:pPr>
      <w:r><w:rPr><w:i/><w:sz w:val="20"/><w:color w:val="94A3B8"/></w:rPr><w:t>作者: ${escapeXml(author)}</w:t></w:r>
    </w:p>
""")
        }

        // Sections
        for (sec in sections) {
            if (!sec.heading.isNullOrBlank()) {
                val fontSize = when (sec.level) {
                    1 -> "36"
                    2 -> "30"
                    else -> "26"
                }
                val color = when (sec.level) {
                    1 -> "1E3A8A"
                    2 -> "0284C7"
                    else -> "334155"
                }
                sb.append("""
    <w:p>
      <w:pPr><w:spacing w:before="280" w:after="120"/></w:pPr>
      <w:r><w:rPr><w:b/><w:sz w:val="$fontSize"/><w:color w:val="$color"/></w:rPr><w:t>${escapeXml(sec.heading)}</w:t></w:r>
    </w:p>
""")
            }

            for (p in sec.paragraphs) {
                sb.append("""
    <w:p>
      <w:pPr><w:spacing w:after="120"/><w:ind w:firstLine="440"/></w:pPr>
      <w:r><w:rPr><w:sz w:val="24"/></w:rPr><w:t>${escapeXml(p)}</w:t></w:r>
    </w:p>
""")
            }

            for (b in sec.bullets) {
                sb.append("""
    <w:p>
      <w:pPr><w:ind w:left="480"/><w:spacing w:after="80"/></w:pPr>
      <w:r><w:rPr><w:b/><w:color w:val="0284C7"/></w:rPr><w:t>• </w:t></w:r>
      <w:r><w:rPr><w:sz w:val="22"/></w:rPr><w:t>${escapeXml(b)}</w:t></w:r>
    </w:p>
""")
            }

            // Tables
            if (sec.tableHeaders.isNotEmpty() && sec.tableRows.isNotEmpty()) {
                sb.append("""
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="0" w:type="auto"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:space="0" w:color="CBD5E1"/>
          <w:left w:val="none"/>
          <w:bottom w:val="single" w:sz="8" w:space="0" w:color="94A3B8"/>
          <w:right w:val="none"/>
          <w:insideH w:val="single" w:sz="4" w:space="0" w:color="E2E8F0"/>
          <w:insideV w:val="none"/>
        </w:tblBorders>
      </w:tblPr>
      <w:tr>
""")
                for (h in sec.tableHeaders) {
                    sb.append("""
        <w:tc>
          <w:tcPr><w:shd w:val="clear" w:color="auto" w:fill="F1F5F9"/></w:tcPr>
          <w:p><w:pPr><w:jc w:val="center"/><w:spacing w:before="80" w:after="80"/></w:pPr><w:r><w:rPr><w:b/><w:color w:val="0F172A"/></w:rPr><w:t>${escapeXml(h)}</w:t></w:r></w:p>
        </w:tc>
""")
                }
                sb.append("      </w:tr>\n")

                for (row in sec.tableRows) {
                    sb.append("      <w:tr>\n")
                    for (cell in row) {
                        sb.append("""
        <w:tc>
          <w:p><w:pPr><w:spacing w:before="60" w:after="60"/></w:pPr><w:r><w:t>${escapeXml(cell)}</w:t></w:r></w:p>
        </w:tc>
""")
                    }
                    sb.append("      </w:tr>\n")
                }
                sb.append("    </w:tbl>\n")
            }
        }

        sb.append("""
    <w:sectPr>
      <w:pgSz w:w="11906" w:h="16838"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
    </w:sectPr>
  </w:body>
</w:document>""")
        return sb.toString()
    }

    // ---------------------------------------------------------------- PPTX XML Generators

    private fun buildPptxContentTypes(slideCount: Int): String {
        val sb = StringBuilder("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
""")
        for (i in 1..slideCount) {
            sb.append("  <Override PartName=\"/ppt/slides/slide$i.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slide+xml\"/>\n")
        }
        sb.append("</Types>")
        return sb.toString()
    }

    private fun buildPptxRootRels(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>"""

    private fun buildPptxPresentationRels(slideCount: Int): String {
        val sb = StringBuilder("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
""")
        for (i in 1..slideCount) {
            sb.append("  <Relationship Id=\"rId$i\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide\" Target=\"slides/slide$i.xml\"/>\n")
        }
        sb.append("</Relationships>")
        return sb.toString()
    }

    private fun buildPptxPresentationXml(slideCount: Int): String {
        val sb = StringBuilder("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"
                xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:sldIdLst>
""")
        for (i in 1..slideCount) {
            val id = 255 + i
            sb.append("    <p:sldId id=\"$id\" r:id=\"rId$i\"/>\n")
        }
        sb.append("""  </p:sldIdLst>
  <p:sldSz cx="12192000" cy="6858000"/>
</p:presentation>""")
        return sb.toString()
    }

    private fun buildPptxSlideRels(): String = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>"""

    private fun buildPptxSlideXml(slide: PptSlide, isCover: Boolean): String {
        val sb = StringBuilder("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
       xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld>
    <p:spTree>
      <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
      <p:grpSpPr/>
""")

        if (isCover) {
            // Main Cover Title & Subtitle
            sb.append("""
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="1000000" y="2000000"/><a:ext cx="10192000" cy="1800000"/></a:xfrm>
        </p:spPr>
        <p:txBody>
          <a:bodyPr anchor="ctr"/>
          <a:p>
            <a:pPr algn="ctr"/>
            <a:r>
              <a:rPr sz="5200" b="1"><a:solidFill><a:srgbClr val="0F172A"/></a:solidFill></a:rPr>
              <a:t>${escapeXml(slide.title)}</a:t>
            </a:r>
          </a:p>
""")
            if (!slide.subtitle.isNullOrBlank()) {
                sb.append("""
          <a:p>
            <a:pPr algn="ctr"/>
            <a:r>
              <a:rPr sz="2400"><a:solidFill><a:srgbClr val="64748B"/></a:solidFill></a:rPr>
              <a:t>${escapeXml(slide.subtitle)}</a:t>
            </a:r>
          </a:p>
""")
            }
            sb.append("""
        </p:txBody>
      </p:sp>
""")
        } else {
            // Content Slide: Top Banner Title
            sb.append("""
      <p:sp>
        <p:nvSpPr><p:cNvPr id="2" name="SlideTitle"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="800000" y="600000"/><a:ext cx="10592000" cy="1000000"/></a:xfrm>
        </p:spPr>
        <p:txBody>
          <a:bodyPr anchor="t"/>
          <a:p>
            <a:r>
              <a:rPr sz="3800" b="1"><a:solidFill><a:srgbClr val="0284C7"/></a:solidFill></a:rPr>
              <a:t>${escapeXml(slide.title)}</a:t>
            </a:r>
          </a:p>
        </p:txBody>
      </p:sp>

      <p:sp>
        <p:nvSpPr><p:cNvPr id="3" name="ContentBody"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
        <p:spPr>
          <a:xfrm><a:off x="800000" y="1800000"/><a:ext cx="10592000" cy="4500000"/></a:xfrm>
        </p:spPr>
        <p:txBody>
          <a:bodyPr anchor="t"/>
""")
            for (b in slide.bullets) {
                sb.append("""
          <a:p>
            <a:pPr marL="288000" indent="-288000"/>
            <a:r>
              <a:rPr sz="2200"><a:solidFill><a:srgbClr val="334155"/></a:solidFill></a:rPr>
              <a:t>• ${escapeXml(b)}</a:t>
            </a:r>
          </a:p>
""")
            }
            if (!slide.notes.isNullOrBlank()) {
                sb.append("""
          <a:p>
            <a:pPr><a:spcBfr><a:spcPts val="2400"/></a:spcBfr></a:pPr>
            <a:r>
              <a:rPr sz="1600" i="1"><a:solidFill><a:srgbClr val="94A3B8"/></a:solidFill></a:rPr>
              <a:t>备注: ${escapeXml(slide.notes)}</a:t>
            </a:r>
          </a:p>
""")
            }
            sb.append("""
        </p:txBody>
      </p:sp>
""")
        }

        sb.append("""
    </p:spTree>
  </p:cSld>
</p:sld>""")
        return sb.toString()
    }
}
